import type {
  HomepageBanner,
  StorefrontBrand,
  StorefrontCategory,
  StorefrontProduct,
} from "@/types/storefront";

const now = new Date("2026-07-10T00:00:00.000Z").toISOString();

export const demoCategories: StorefrontCategory[] = [
  {
    id: "cat-load",
    name: "Mobile Load",
    slug: "mobile-load",
    description: "Fast prepaid load and data promos.",
    imageUrl: "/product-art/mobile-load.svg",
  },
  {
    id: "cat-game",
    name: "Game Credits",
    slug: "game-credits",
    description: "Top-ups for popular games.",
    imageUrl: "/product-art/game-credits.svg",
  },
  {
    id: "cat-voucher",
    name: "Gift Vouchers",
    slug: "gift-vouchers",
    description: "Digital codes for gifting and shopping.",
    imageUrl: "/product-art/gift-voucher.svg",
  },
  {
    id: "cat-accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Everyday tech add-ons.",
    imageUrl: "/product-art/accessories.svg",
  },
];

export const demoBrands: StorefrontBrand[] = [
  { id: "brand-globe", name: "Globe", slug: "globe", logoUrl: null },
  { id: "brand-smart", name: "Smart", slug: "smart", logoUrl: null },
  { id: "brand-garena", name: "Garena", slug: "garena", logoUrl: null },
  { id: "brand-play", name: "PlayPass", slug: "playpass", logoUrl: null },
  { id: "brand-tech", name: "TechMate", slug: "techmate", logoUrl: null },
];

function image(id: string, url: string, alt: string) {
  return [{ id, url, alt, isPrimary: true }];
}

export const demoProducts: StorefrontProduct[] = [
  {
    id: "prod-globe-99",
    name: "GoSURF 99 Data Promo",
    slug: "gosurf-99-data-promo",
    description: "Prepaid data promo with reliable everyday browsing allowance.",
    specifications: {
      Delivery: "Digital fulfillment",
      Validity: "7 days",
      Redemption: "Sent to registered mobile number",
    },
    keywords: ["load", "data", "globe", "internet"],
    brand: demoBrands[0],
    category: demoCategories[0],
    priceCents: 9900,
    salePriceCents: 8900,
    badge: "Sale",
    isFeatured: true,
    stock: 42,
    images: image("img-globe-99", "/product-art/mobile-load.svg", "Mobile load product"),
    variants: [
      {
        id: "var-globe-own",
        name: "Send to my number",
        sku: "GLOBE-99-OWN",
        priceCents: null,
        salePriceCents: null,
        attributes: { Delivery: "Own number" },
        stock: 32,
      },
      {
        id: "var-globe-gift",
        name: "Send as gift",
        sku: "GLOBE-99-GIFT",
        priceCents: null,
        salePriceCents: null,
        attributes: { Delivery: "Recipient number" },
        stock: 10,
      },
    ],
    createdAt: now,
  },
  {
    id: "prod-smart-149",
    name: "Smart Power Data 149",
    slug: "smart-power-data-149",
    description: "A flexible prepaid data code for work, school, and streaming.",
    specifications: {
      Delivery: "Digital code",
      Validity: "7 days",
      Network: "Smart",
    },
    keywords: ["smart", "load", "data", "promo"],
    brand: demoBrands[1],
    category: demoCategories[0],
    priceCents: 14900,
    salePriceCents: null,
    badge: "New",
    isFeatured: true,
    stock: 24,
    images: image("img-smart-149", "/product-art/mobile-load.svg", "Data promo product"),
    variants: [],
    createdAt: now,
  },
  {
    id: "prod-garena-shells",
    name: "Garena Shells 100",
    slug: "garena-shells-100",
    description: "Digital game credit for supported Garena titles.",
    specifications: {
      Delivery: "Instant digital code",
      Region: "Philippines",
      Usage: "Redeem on Garena account",
    },
    keywords: ["game", "garena", "shells", "credits"],
    brand: demoBrands[2],
    category: demoCategories[1],
    priceCents: 10000,
    salePriceCents: 9500,
    badge: "Featured",
    isFeatured: true,
    stock: 18,
    images: image("img-garena", "/product-art/game-credits.svg", "Game credits product"),
    variants: [
      {
        id: "var-garena-code",
        name: "Digital code",
        sku: "GARENA-100-CODE",
        priceCents: null,
        salePriceCents: null,
        attributes: { Format: "Code" },
        stock: 18,
      },
    ],
    createdAt: now,
  },
  {
    id: "prod-playpass-250",
    name: "PlayPass Wallet 250",
    slug: "playpass-wallet-250",
    description: "Wallet credit for in-game items and digital entertainment.",
    specifications: {
      Delivery: "Digital code",
      Amount: "PHP 250",
      Support: "Selected games",
    },
    keywords: ["wallet", "game", "credits", "playpass"],
    brand: demoBrands[3],
    category: demoCategories[1],
    priceCents: 25000,
    salePriceCents: 23500,
    badge: "Sale",
    isFeatured: false,
    stock: 8,
    images: image("img-playpass", "/product-art/game-credits.svg", "Wallet credits product"),
    variants: [],
    createdAt: now,
  },
  {
    id: "prod-gift-500",
    name: "Digital Gift Voucher 500",
    slug: "digital-gift-voucher-500",
    description: "A clean giftable voucher for digital purchases.",
    specifications: {
      Delivery: "Email code",
      Amount: "PHP 500",
      Expiry: "12 months",
    },
    keywords: ["voucher", "gift", "code"],
    brand: demoBrands[3],
    category: demoCategories[2],
    priceCents: 50000,
    salePriceCents: null,
    badge: "Featured",
    isFeatured: true,
    stock: 15,
    images: image("img-voucher", "/product-art/gift-voucher.svg", "Gift voucher product"),
    variants: [],
    createdAt: now,
  },
  {
    id: "prod-cable",
    name: "TechMate Fast Charge Cable",
    slug: "techmate-fast-charge-cable",
    description: "Durable charging cable for everyday phone and tablet use.",
    specifications: {
      Length: "1 meter",
      Connector: "USB-C",
      Warranty: "7 days replacement",
    },
    keywords: ["cable", "charger", "accessory"],
    brand: demoBrands[4],
    category: demoCategories[3],
    priceCents: 19900,
    salePriceCents: 15900,
    badge: "Sale",
    isFeatured: false,
    stock: 0,
    images: image("img-cable", "/product-art/accessories.svg", "Charging cable product"),
    variants: [
      {
        id: "var-cable-black",
        name: "Black",
        sku: "CABLE-BLK",
        priceCents: null,
        salePriceCents: null,
        attributes: { Color: "Black" },
        stock: 0,
      },
    ],
    createdAt: now,
  },
];

export const demoBanners: HomepageBanner[] = [
  {
    id: "banner-main",
    title: "Digital deals delivered fast",
    subtitle: "Browse load, game credits, vouchers, and accessories in one storefront.",
    imageUrl: "/product-art/marketplace-hero.svg",
    href: "/products",
  },
  {
    id: "banner-games",
    title: "Game credits ready",
    subtitle: "Top-up codes and wallet credits for your next match.",
    imageUrl: "/product-art/game-credits.svg",
    href: "/category/game-credits",
  },
];
